---
# version check for all supported roles
submodules_versioncheck: true
packages__submodules_versioncheck: "{{ submodules_versioncheck }}"
check_ansible_version: '2.15.2'

# l3d.packages
packages__install_advanced: true
packages__install_cli: true

# do1jlr.ntp
ntp_set_time_zone: true
ntp_servers:
  - ntp3.hetzner.de iburst
  - ntp2.hetzner.de iburst
  - ntp1.hetzner.de iburst
  - ptbtime1.ptb.de
  - ptbtime3.ptb.de
  - 1.pool.ntp.org iburst
  - 2.pool.ntp.org iburst
  - 3.pool.ntp.org iburst

# prometheus.prometeus.node_exporter
node_exporter_web_listen_address: '127.0.0.1:9100'

# l3d.users
l3d_users__default_users:
  - name: 'l3d'
    state: 'present'
    shell: '/bin/bash'
    create_home: true
    admin: true
    admin_nopassword: true
    admin_commands: 'ALL'
    pubkeys: |
       ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPvvXN33GwkTF4ZOwPgF21Un4R2z9hWUuQt1qIfzQyhC
       ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAG65EdcM+JLv0gnzT9LcqVU47Pkw0SqiIg7XipXENi8
       ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJz7zEvUVgJJJsIgfG3izsqYcM22IaKz4jGVUbNRL2PX

# l3d.users.user
l3d_users__create_ansible: true
l3d_users__ansible_user_state: 'present'
l3d_users__set_ansible_ssh_keys: true
l3d_users__ansible_ssh_keys: "{{ lookup('url', 'https://github.com/do1jlr.keys', split_lines=False) }}"

# do1jlr.users
admins:
  - l3d
  - ansible
