---
- name: import mail database config
  become: true
  community.mysql.mysql_db:
    name: vmail
    encoding: 'utf8'
    state: import
    target: '/root/.mariadb_schema/config.sql'

- name: create database schema
  become: true
  community.mysql.mysql_db:
    name: vmail
    encoding: 'utf8'
    state: import
    target: '/root/.mariadb_schema/schema.sql'
