---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: configure local hostnames
  include_tasks: hosts.yml

- name: configure vmail user
  include_tasks: user.yml

- name: configure mariadb
  include_tasks: mariadb.yml

