---
- name: create database schema store dir
  become: true
  file:
    path: /root/.mariadb_schema
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Copy database schema
  become: true
  copy:
    src: files/schema.sql
    dest: /root/.mariadb_schema/schema.sql
    mode: '0644'
  notify: create database schema

- name: Copy mail config
  become: true
  template:
    src: templates/mysqlconfig.sql.j2
    dest: /root/.mariadb_schema/config.sql
    mode: '0644'
  notify: import mail database config
