---
postgres_users_no_log: false
users:
  l3d:
    - l3d@pinkie.l3d.yt
    - l3d@mobile.l3d.yt
    - l3d@backup.l3d.yt
    - l3d@derpy.l3d.yt
    - l3d@backup-rsa.l3d.yt
    - l3d@business.wingcon.com
  webwaffel:
    - l3d@pinkie.l3d.yt
    - l3d@mobile.l3d.yt
    - l3d@backup.l3d.yt
    - l3d@derpy.l3d.yt
    - l3d@backup-rsa.l3d.yt
    - l3d@business.wingcon.com
  webwaffelpodcast:
    - l3d@pinkie.l3d.yt
    - l3d@mobile.l3d.yt
    - l3d@backup.l3d.yt
    - l3d@derpy.l3d.yt
    - l3d@backup-rsa.l3d.yt
    - l3d@business.wingcon.com
  wtfpreview:
    - l3d@pinkie.l3d.yt
    - l3d@mobile.l3d.yt
    - l3d@backup.l3d.yt
    - l3d@derpy.l3d.yt
    - l3d@backup-rsa.l3d.yt
    - l3d@business.wingcon.com
  files:
    - l3d@pinkie.l3d.yt
    - l3d@mobile.l3d.yt
    - l3d@backup.l3d.yt
    - l3d@derpy.l3d.yt
    - l3d@backup-rsa.l3d.yt
    - l3d@business.wingcon.com

sshd__allowed_users:
  - "root"
  - "ansible"
  - "l3d"
  - "webwaffel"
  - "webwaffelpodcast"
  - "gitea"
  - "wtfpreview"
  - "files"

sshd__allowed_groups:
  - "root"
  - "ansible"
  - "l3d"
  - "webwaffel"
  - "webwaffelpodcast"
  - "gitea"
  - "wtfpreview"
  - "files"

accounts:
  - 'l3d'
  - 'webwaffel'
  - 'webwaffelpodcast'
  - 'wtfpreview'
  - "files"

nginx_sites:
  - name: 'c3woc.de'
    webroot:
      user: 'webwaffel'
  - name: 'www.c3woc.de'
  - name: 'waffel.tv'
  - name: 'www.waffel.tv'
  - name: 'c3woc.org'
  - name: 'waffel.li'
  - name: 'www.waffel.li'
  - name: 'www.c3woc.org'
  - name: 'c3woc.eu'
  - name: 'www.c3woc.eu'
  - name: 'c3woc.cn'
  - name: 'www.c3woc.cn'
  - name: 'waffeln.eskalieren.jetzt'
  - name: 'waffeln.fehlerfrei.org'
  - name: 'www.waffeln.fehlerfrei.org'
  - name: 'waffel.shop'
  - name: 'www.waffel.shop'
  - name: 'l3d.space'
  - name: 'www.l3d.space'
  - name: 'ansible.l3d.space'
  - name: 'www.ansible.l3d.space'
  - name: 'l3d.yt'
  - name: 'www.l3d.yt'
  - name: 'l3d.ch'
  - name: 'www.l3d.ch'
  - name: 'l3d.me'
  - name: 'www.l3d.me'
  - name: 'podcast.c3woc.de'
    webroot:
      user: 'webwaffelpodcast'
  - name: 'www.podcast.c3woc.de'
  - name: 'podcast.c3woc.org'
  - name: 'www.podcast.c3woc.org'
  - name: 'podcast.c3vvoc.de'
  - name: 'www.podcast.c3vvoc.de'
  - name: 'podcast.c3woc.eu'
  - name: 'www.podcast.c3woc.eu'
  - name: 'angel.systems'
  - name: 'www.angel.systems'
  - name: 'einhornsystem.de'
  - name: 'www.einhornsystem.de'
  - name: 'backwesen.de'
  - name: 'www.backwesen.de'
  - name: 'c3nom.de'
  - name: 'www.c3nom.de'
  - name: 'c3doc.de'
  - name: 'www.c3doc.de'
  - name: 'wtf-kooperative.de'
  - name: 'www.wtf-kooperative.de'
  - name: 'cyber.yt'
  - name: 'preview.wtf-kooperative.de'
    webroot:
      user: 'wtfpreview'
  - name: 'www.preview.wtf-kooperative.de'
  - name: 'files.l3d.ch'
    webroot:
      user: 'files'
  - name: 'www.files.l3d.ch'

acme_notification_email: "{{ _acme_notification_email }}"

# firewall
fail2ban_destemail: "{{ _fail2ban_destemail }}"
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

# gitea settings
gitea_app_name: 'backwesen.de'
gitea_http_domain: 'backwesen.de'
gitea_root_url: 'https://backwesen.de'
gitea_protocol: 'http'
gitea_shell: '/bin/bash'
gitea_lfs_server_enabled: true
gitea_lfs_content_path: "{{ gitea_home }}/data/lfs"
gitea_lfs_jwt_secret: "{{ _gitea_lfs_jwt_secret }}"
gitea_oauth2_jwt_secret: "{{ _gitea_oauth2_jwt_secret }}"
gitea_repository_root: "{{ gitea_home }}/repos"
gitea_ssh_domain: "{{ gitea_http_domain }}"
gitea_start_ssh: "{{ _gitea_start_ssh }}"
gitea_ssh_port: 22
gitea_require_signin: false

# gitea db
gitea_db_type: mysql
gitea_db_host: "{{ _gitea_db_host }}"
gitea_db_name: "{{ _gitea_db_name }}"
gitea_db_user: "{{ _gitea_db_user }}"
gitea_db_password: "{{ _gitea_db_password }}"
gitea_db_ssl: "{{ _gitea_db_ssl }}"
gitea_db_path: false

# gitea mail
gitea_mailer_enabled: true
gitea_mailer_host: 'mail01.l3d.space:465'
gitea_mailer_from: 'git@backwesen.de'
gitea_mailer_user: 'git@backwesen.de'
gitea_mailer_password: "{{ _gitea_mail_password }}"

# gitea other
gitea_fail2ban_enabled: true
gitea_metrics_enabled: true
gitea_metrics_token: "{{ _gitea_metrics_token }}"
gitea_repo_indexer_enabled: true
gitea_enable_notify_mail: true

# gitea secrets
gitea_secret_key: "{{ _gitea_secret_key }}"
gitea_internal_token: "{{ _gitea_internal_token }}"
gitea_disable_git_hooks: "{{ _gitea_disable_git_hooks }}"
gitea_disable_registration: "{{ _gitea_disable_registration }}"
gitea_show_registration_button: "{{ _gitea_show_registration_button }}"
