---
l3d_users__local_users:
  - name: 'mxusr'
    state: 'present'
    admin: false
    pubkeys: "{{ lookup('url', 'https://github.com/do1jlr.keys', split_lines=False) }}"
  - name: 'rustdesk-web'
    state: 'present'
    admin: false
    pubkeys: "{{ lookup('url', 'https://github.com/do1jlr.keys', split_lines=False) }}"

acme_domain_unwant_list: []
#  - name: 'example.com'

nginx_sites:
  - name: 'services.l3d.ch'
    webroot:
      user: 'mxusr'
  - name: 'node-exporter.services.l3d.ch'
  - name: 'nginx-exporter.services.l3d.ch'
  - name: 'rustdesk.l3d.ch'
    webroot:
      user: 'rustdesk-web'
  - name: 'grafana.winkekatze.tv'
  - name: 'www.grafana.winkekatze.tv'

# letsencrypt
acme_notification_email: "{{ _acme_notification_email }}"

# acmetool config
acme_reload_services:
  - 'nginx'

# firewall
fail2ban_destemail: "{{ _fail2ban_destemail }}"
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
  - "21115"
  - "21116"
  - "21117"

firewall_allowed_udp_ports:
  - "21116"
  - "51820"

# l3d.time.ntp
ntp_statistics: true

# l3d.nginx_exporter
nginx_exporter_listen_address: '127.0.0.1:9113'
nginx_exporter_scrape_uri: 'https://node-exporter.mx.l3d.ch/nginx_status'

# grafana.grafana-grafana
grafana_alerting: {}
grafana_address: '127.0.0.1'
grafana_instance: 'grafana.l3d.ch'
grafana_users:
  allow_sign_up: false
  auto_assign_org_role: Viewer
  default_theme: dark

grafana_dashboards:
  - dashboard_id: '1860'
    revision_id: '37'
    datasource: '{{ grafana_datasources.0.name }}'
  - dashboard_id: '12708'
    revision_id: '1'
    datasource: '{{ grafana_datasources.0.name }}'
  - dashboard_id: '19688'
    revision_id: '1'
    datasource: '{{ grafana_datasources.0.name }}'

# l3d.rustdesk
rustdesk__relay_server_domain: 'rustdesk.l3d.ch'
