---
l3d_users__local_users:
  - name: 'mxusr'
    state: 'present'
    admin: false
    pubkeys: "{{ lookup('url', 'https://github.com/do1jlr.keys', split_lines=False) }}"

acme_domain_unwant_list: []
#  - name: 'example.com'

nginx_sites:
  - name: 'services.l3d.ch'
    webroot:
      user: 'mxusr'
  - name: 'node-exporter.services.l3d.ch'
  - name: 'nginx-exporter.services.l3d.ch'

# letsencrypt
acme_notification_email: "{{ _acme_notification_email }}"

# acmetool config
acme_reload_services:
  - 'nginx'

# firewall
fail2ban_destemail: "{{ _fail2ban_destemail }}"
firewall_allowed_tcp_ports:
  - "22"
#  - "25"
  - "80"
#  - "143"
  - "443"
#  - "465"
#  - "587"
#  - "993"
#  - "4190"
#  - "42023"

# l3d.time.ntp
ntp_statistics: true

# l3d.nginx_exporter
nginx_exporter_listen_address: '127.0.0.1:9113'
nginx_exporter_scrape_uri: 'https://node-exporter.mx.l3d.ch/nginx_status'
