---
users:
  l3d:
    - l3d@pinkie.l3d.yt
    - l3d@mobile.l3d.yt
    - l3d@backup.l3d.yt
    - l3d@derpy.l3d.yt
    - l3d@backup-rsa.l3d.yt
    - l3d@business.wingcon.com
  mailwebuser:
    - l3d@pinkie.l3d.yt
    - l3d@mobile.l3d.yt
    - l3d@backup.l3d.yt
    - l3d@derpy.l3d.yt
    - l3d@backup-rsa.l3d.yt
    - l3d@business.wingcon.com

accounts:
  - l3d
  - mailwebuser

# mail domains
additional_dns_maildomains: 'mail.l3d.space imap.l3d.space smtp.l3d.space'

# mailserver
mailserver_domain: "{{ _mailserver_domain }}"

# mail mysql access
mailserver__mysql_password: "{{ _mailserver__mysql_password }}"
mailserver__mysql_user: "{{ _mailserver__mysql_user }}"
mailserver__mysql_database: "{{ _mailserver__mysql_database }}"
mailserver__ssl_cert: "{{ _mailserver__ssl_cert }}"
mailserver__ssl_key: "{{ _mailserver__ssl_key }}"
postfix__db_user: "{{ _mailserver__mysql_user }}"
postfix__db_password: "{{ _mailserver__mysql_password }}"
postfix__db_name: "{{ _mailserver__mysql_database }}"

nginx_sites:
  - name: 'mail.l3d.space'
    webroot:
      user: 'mailwebuser'

# letsencrypt
acme_notification_email: "{{ _acme_notification_email }}"

# firewall
fail2ban_destemail: "{{ _fail2ban_destemail }}"
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"

# mysql
mysql_bind_address: "{{ _mysql_bind_address }}"
mysql_root_password: "{{ _mysql_root_password }}"

# postfix
postfix__myhostname: "{{ mailserver_domain }}"
postfix__tls_cert: "{{ mailserver__ssl_cert }}"
postfix__tls_key: "{{ mailserver__ssl_key }}"
