---
acme_domain_unwant_list: []
#  - name: 'example.com'

nginx_sites:
  - name: 'etebase.l3d.ch'
  - name: 'grafana.l3d.ch'
  - name: 'www.grafana.l3d.ch'

acme_notification_email: "{{ _acme_notification_email }}"

# firewall
fail2ban_destemail: "{{ _fail2ban_destemail }}"
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

# do1jlr.etebase
etebase__allowed_hosts_allowed_host1: 'etebase.l3d.ch'
etebase__restart_webserver: true
etebase__systemd_setup: true
etebase__create_backup: true

# acmetool config
acme_reload_services:
  - 'nginx'
