---
acme_domain_unwant_list: []
#  - name: 'example.com'

nginx_sites:
  - name: 'etebase.l3d.ch'
  - name: 'grafana.l3d.ch'
  - name: 'www.grafana.l3d.ch'
  - name: 'node-exporter.services.l3d.space'
  - name: 'nginx-exporter.services.l3d.space'

acme_notification_email: "{{ _acme_notification_email }}"

# firewall
fail2ban_destemail: "{{ _fail2ban_destemail }}"
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"

# do1jlr.etebase
etebase__allowed_hosts_allowed_host1: 'etebase.l3d.ch'
etebase__restart_webserver: true
etebase__systemd_setup: true
etebase__create_backup: true

# acmetool config
acme_reload_services:
  - 'nginx'

# grafana.grafana-grafana
grafana_address: '127.0.0.1'
grafana_instance: 'grafana.l3d.ch'
grafana_users:
  allow_sign_up: false
  auto_assign_org_role: Viewer
  default_theme: dark

grafana_dashboards:
  - dashboard_id: '1860'
    revision_id: '33'
    datasource: '{{ grafana_datasources.0.name }}'
  - dashboard_id: '12708'
    revision_id: '1'
    datasource: '{{ grafana_datasources.0.name }}'

# l3d.nginx_exporter
nginx_exporter_listen_address: '127.0.0.1:9113'
nginx_exporter_scrape_uri: 'https://node-exporter.services.l3d.space/stub_status'
