---
# pretix
pretix__name: 'Patches'
pretix__address: 'https://patch.l3d.ch'

# nginx
acme_domain_unwant_list:
  - name: 'patch.l3d.space'

nginx_sites:
  - name: 'patch.l3d.ch'

acme_notification_email: "{{ _acme_notification_email }}"

# firewall
fail2ban_destemail: "{{ _fail2ban_destemail }}"
firewall_allowed_tcp_ports:
  - "22"
  - "80"
  - "443"
